export const stories = [
  {
    profileImg: "./assets/profile-1.png",
    profileName: "Behance",
    title: [
      "Showcasing creative",
      "portfolios and projects",
      "from top designers",
    ],
    linkLabel: "Read More",
    linkSrc: "behance.net",
    storyImg: "./assets/story-1.png",
  },
  {
    profileImg: "./assets/profile-2.png",
    profileName: "Dribbble",
    title: ["Inspiring design", "ideas and visual", "creations from experts"],
    linkLabel: "Discover",
    linkSrc: "dribbble.com",
    storyImg: "./assets/story-2.png",
  },
  {
    profileImg: "./assets/profile-3.png",
    profileName: "Awwwards",
    title: ["Award-winning web", "design and development", "projects"],
    linkLabel: "Check It Out",
    linkSrc: "awwwards.com",
    storyImg: "./assets/story-3.png",
  },
  {
    profileImg: "./assets/profile-4.png",
    profileName: "Adobe",
    title: ["Curated design", "inspiration for", "creative professionals"],
    linkLabel: "Adobe More",
    linkSrc: "adobe.com",
    storyImg: "./assets/story-4.png",
  },
  {
    profileImg: "./assets/profile-5.png",
    profileName: "Creative Bloq",
    title: ["The latest in", "design trends", "and tutorials"],
    linkLabel: "Explore",
    linkSrc: "creativebloq.com",
    storyImg: "./assets/story-5.png",
  },
  {
    profileImg: "./assets/profile-6.png",
    profileName: "Smashing Magazine",
    title: ["Practical tips", "for web designers", "and developers"],
    linkLabel: "Visit Site",
    linkSrc: "smashingmagazine.com",
    storyImg: "./assets/story-6.png",
  },
];
